version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: alumni_postgres
    environment:
      POSTGRES_DB: alumni_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourdad
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - alumni_network

  # Rust Backend
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: alumni_backend
    environment:
      DATABASE_URL: postgresql://postgres:yourdad@postgres:5432/alumni_db
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      PORT: 3000
      ENVIRONMENT: development
      RUST_LOG: info
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - alumni_network
    volumes:
      - ./be:/app
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/app/target

  # Svelte Frontend
  frontend:
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: alumni_frontend
    environment:
      PUBLIC_API_URL: http://localhost:3000
      PUBLIC_APP_NAME: Alumni Network
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - alumni_network
    volumes:
      - ./fe:/app
      - /app/node_modules

volumes:
  postgres_data:
  cargo_cache:
  target_cache:

networks:
  alumni_network:
    driver: bridge
